### ISSUE TITLE
block_utils

### ISSUE THREAD

**Issue by evgenyleushkin** [google/deeppolisher#2]
Hi all,

When trying to execute **find_homozygous_regions.py** ran into a problem of missing **block_utils** module.
Could only find **up42-blockutils**, but that didn't seem to be correct, as there was nothing about Alignment there.

Best,

Evgeny Leushkin

**Comment by kishwarshafin** [comment]
@evgenyleushkin ,

Can you please show how you are running the script? Through docker?
